### ISSUE TITLE
Missing plustrain.sh file

### ISSUE THREAD

**Issue by raphaelmerx** [Shreeshrii/tessdata_jav_java#1]
We're keen to revive efforts on adding Javanese and Balinese script to tesseract. I wanted to continue training for Javanese script, but found that `plustrain.sh`, which is mentioned in the README, has not been committed to this repo.

**Comment by Shreeshrii** [comment]
Traning with bash scripts is no longer supported by Tesseract. Please see the tesstrain repo for Makefile and python based training.

Instead of `plustrain.sh` you can use 'layertrain.sh`.
